#!/usr/bin/env node
/**
 * scaffold.mjs — scaffold a self-contained UI test harness into a target repo.
 *
 * Usage:
 *   node .claude/skills/ui-test/script/scaffold.mjs <target-repo-path>
 *   bash .claude/skills/ui-test/script/ui-test.sh init <target-repo-path>
 *
 * Creates (or updates) <target-repo>/tests/ui/ with a portable Playwright harness:
 *
 *   tests/ui/
 *     lib/harness.mjs        portable harness (reads local config, no skill deps)
 *     lib/config.mjs         standalone config: apps.json + env-var credentials
 *     lib/auth.mjs           login helper (verbatim from skill)
 *     run.mjs                batch spec runner (verbatim from skill)
 *     config/apps.json       per-app URL + viewport (local, not .claude/config.json)
 *     specs/_example.smoke.mjs    starter spec: page loads
 *     specs/_example.geometry.mjs starter spec: body fills viewport
 *     snippets/              app-specific helpers (verbatim copies)
 *     package.json           { playwright }
 *     .gitignore             .runs/, node_modules/
 *     README.md              quick-start guide
 *
 * If tests/ui/ already exists, lib/ + run.mjs are updated in-place;
 * specs/, config/apps.json, package.json, .gitignore, and README.md are
 * left alone (to preserve user edits). Pass --force to overwrite everything.
 *
 * After scaffolding, no dependency on .claude/skills/ui-test/ remains:
 *   cd <target-repo>
 *   npm install --prefix tests/ui
 *   npx --prefix tests/ui playwright install --with-deps chromium
 *   UITEST_APP_PASSWORD=... node tests/ui/run.mjs \
 *     --out tests/ui/.runs/smoke tests/ui/specs/_example.smoke.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SKILL_DIR = path.resolve(__dirname, '..');

// ── Argument parsing ─────────────────────────────────────────────────────────

const args = process.argv.slice(2);
if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
  console.log('Usage: node scaffold.mjs <target-repo-path> [--force]');
  process.exit(args.length === 0 ? 2 : 0);
}

const FORCE = args.includes('--force');
const TARGET_REPO = path.resolve(args.find(a => !a.startsWith('--')) || '');
const UI_DIR = path.join(TARGET_REPO, 'tests', 'ui');
const exists = fs.existsSync(UI_DIR);

console.log(`Scaffolding UI test harness`);
console.log(`  Skill:  ${SKILL_DIR}`);
console.log(`  Target: ${UI_DIR}`);
console.log(`  Mode:   ${exists ? (FORCE ? 'force overwrite' : 'update (lib/ + run.mjs only)') : 'create'}`);
console.log();

// ── Helpers ──────────────────────────────────────────────────────────────────

function mkdirp(p) { fs.mkdirSync(p, { recursive: true }); }

function write(dest, content, { skipIfExists = false } = {}) {
  if (skipIfExists && fs.existsSync(dest)) {
    console.log(`  skip (exists): ${path.relative(TARGET_REPO, dest)}`);
    return;
  }
  fs.writeFileSync(dest, content, 'utf8');
  console.log(`  write: ${path.relative(TARGET_REPO, dest)}`);
}

function copyFile(src, dest, { skipIfExists = false } = {}) {
  if (skipIfExists && fs.existsSync(dest)) {
    console.log(`  skip (exists): ${path.relative(TARGET_REPO, dest)}`);
    return;
  }
  fs.copyFileSync(src, dest);
  console.log(`  copy:  ${path.relative(TARGET_REPO, dest)}`);
}

function copyDir(src, dest) {
  mkdirp(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else { fs.copyFileSync(s, d); console.log(`  copy:  ${path.relative(TARGET_REPO, d)}`); }
  }
}

// ── Create directory tree ────────────────────────────────────────────────────

mkdirp(path.join(UI_DIR, 'lib'));
mkdirp(path.join(UI_DIR, 'config'));
mkdirp(path.join(UI_DIR, 'specs'));

// ── lib/harness.mjs — adapted from skill harness ─────────────────────────────
// Two substitutions make the skill harness portable:
//   1. Import path: '../../script/config.mjs' → './config.mjs'   (local standalone config)
//   2. SKILL_DIR: path.resolve(__dirname, '..', '..') → path.resolve(__dirname, '..') (tests/ui/)
// Everything else is identical so updates to the skill harness flow through on re-scaffold.

{
  const src = path.join(SKILL_DIR, 'playwright', 'lib', 'harness.mjs');
  let code = fs.readFileSync(src, 'utf8');
  code = code.replace(
    `from '../../script/config.mjs'`,
    `from './config.mjs'`,
  );
  code = code.replace(
    `const SKILL_DIR = path.resolve(__dirname, '..', '..');`,
    `const SKILL_DIR = path.resolve(__dirname, '..');`,
  );
  // Prepend a note so readers understand this is a generated file
  const note = `// GENERATED by scaffold.mjs — re-run "node skills/ui-test/script/scaffold.mjs <repo> (adjust path to where the skill is installed)" to update.\n// Edit specs/*, config/apps.json, and lib/config.mjs freely; don't edit this file by hand.\n\n`;
  write(path.join(UI_DIR, 'lib', 'harness.mjs'), note + code);
}

// ── lib/auth.mjs — verbatim ──────────────────────────────────────────────────

copyFile(
  path.join(SKILL_DIR, 'playwright', 'lib', 'auth.mjs'),
  path.join(UI_DIR, 'lib', 'auth.mjs'),
);

// ── lib/config.mjs — standalone config loader ─────────────────────────────────
// Reads app URL + viewport from tests/ui/config/apps.json.
// Reads credentials from env vars so secrets stay out of the repo:
//   UITEST_<APPKEY>_EMAIL, UITEST_<APPKEY>_PASSWORD  (app-scoped)
//   UITEST_EMAIL, UITEST_PASSWORD                    (generic fallback)
//   UITEST_<APPKEY>_NAME                             (persona display name)
// Exports the same appConfig() + selectCredential() interface as the skill's config.mjs
// so harness.mjs works without changes.

write(
  path.join(UI_DIR, 'lib', 'config.mjs'),
  `// GENERATED by scaffold.mjs — re-run the scaffold to update.
// Standalone config loader: reads apps.json + env-var credentials.
// Same export surface as the skill's config.mjs so harness.mjs works unchanged.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UI_DIR = path.resolve(__dirname, '..');  // tests/ui/

function loadApps() {
  const p = path.join(UI_DIR, 'config', 'apps.json');
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch { return {}; }
}

// Build credential list from environment variables.
// Convention: UITEST_<APPKEY>_EMAIL + UITEST_<APPKEY>_PASSWORD (app-scoped)
//             UITEST_EMAIL + UITEST_PASSWORD (generic fallback)
// Example:  UITEST_APP_EMAIL=dev@example.com UITEST_APP_PASSWORD=secret
function envcred(appKey) {
  const prefix = \`UITEST_\${appKey.toUpperCase().replace(/-/g, '_')}\`;
  const email = process.env[\`\${prefix}_EMAIL\`] || process.env.UITEST_EMAIL || null;
  const password = process.env[\`\${prefix}_PASSWORD\`] || process.env.UITEST_PASSWORD || null;
  const name = process.env[\`\${prefix}_NAME\`] || process.env.UITEST_NAME || 'default';
  if (!email && !password) return [];
  return [{ name, email: email || '', password: password || null, roles: ['editor'] }];
}

export function appConfig(appKey) {
  const apps = loadApps();
  const entry = apps[appKey];
  if (!entry) return null;
  return {
    url: entry.url,
    credentials: envcred(appKey),
    _appsEntry: entry,
  };
}

export function selectCredential(appCfg, selector) {
  const creds = appCfg?.credentials || [];
  if (creds.length === 0) return null;
  if (selector) {
    const sel = String(selector).toLowerCase();
    const byName = creds.find(c => String(c.name || '').toLowerCase() === sel);
    if (byName) return byName;
    const byRole = creds.find(c => (c.roles || []).some(r => String(r).toLowerCase() === sel));
    if (byRole) return byRole;
  }
  return creds[0];
}

export function repoRoot() { return UI_DIR; }
`,
);

// ── run.mjs — verbatim copy ───────────────────────────────────────────────────

copyFile(
  path.join(SKILL_DIR, 'playwright', 'run.mjs'),
  path.join(UI_DIR, 'run.mjs'),
);

// ── snippets/ — verbatim copy ─────────────────────────────────────────────────

const snippetsSrc = path.join(SKILL_DIR, 'playwright', 'snippets');
if (fs.existsSync(snippetsSrc)) {
  copyDir(snippetsSrc, path.join(UI_DIR, 'snippets'));
}

// ── config/apps.json — template (skip if exists) ─────────────────────────────

write(
  path.join(UI_DIR, 'config', 'apps.json'),
  JSON.stringify({
    app: {
      _comment: "URL the tests drive — update to match your dev server",
      url: "http://localhost:8080",
      viewport_mobile: { width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true },
      viewport_desktop: { width: 1440, height: 900 },
    },
  }, null, 2) + '\n',
  { skipIfExists: !FORCE },
);

// ── specs/_example.smoke.mjs ─────────────────────────────────────────────────

write(
  path.join(UI_DIR, 'specs', '_example.smoke.mjs'),
  `// _example.smoke.mjs — starter spec: page loads and title is non-empty.
// This spec does NOT require login credentials — it just loads the root URL.
// Copy and extend it for your own tests.
//
// Run standalone (from repo root):
//   node tests/ui/run.mjs --out tests/ui/.runs/smoke tests/ui/specs/_example.smoke.mjs
//
// Configure the URL in tests/ui/config/apps.json.

import { runTest } from '../lib/harness.mjs';

await runTest(
  { id: 0, name: 'Smoke — page loads', app: 'app', viewport: 'desktop' },
  async (t) => {
    await t.step('navigate to root', async () => {
      await t.goto('/');
      const title = await t.page.title();
      t.check('page title non-empty', title.length > 0, \`title="\${title}"\`);
      t.log(\`title: \${title}\`);
      await t.screenshot('root');
    });

    await t.step('body geometry', async () => {
      const box = await t.page.locator('body').first().boundingBox();
      const vp = t.page.viewportSize();
      t.check('body width ~= viewport', Math.abs(box.width - vp.width) < 20,
        \`body.width=\${box.width} viewport.width=\${vp.width}\`);
      t.check('body height > 100', box.height > 100, \`body.height=\${box.height}\`);
      t.log(\`body: \${box.width}×\${box.height}  viewport: \${vp.width}×\${vp.height}\`);
    });
  }
);
`,
  { skipIfExists: !FORCE },
);

// ── specs/_example.geometry.mjs ───────────────────────────────────────────────

write(
  path.join(UI_DIR, 'specs', '_example.geometry.mjs'),
  `// _example.geometry.mjs — starter geometry assertion spec.
// Demonstrates checking element geometry against expected dimensions.
// Adapt selector + expected sizes for your own UI components.
//
// Run:  node tests/ui/run.mjs --out tests/ui/.runs/geom tests/ui/specs/_example.geometry.mjs

import { runTest } from '../lib/harness.mjs';

await runTest(
  { id: 1, name: 'Geometry — layout sanity', app: 'app', viewport: 'desktop' },
  async (t) => {
    await t.step('navigate', async () => { await t.goto('/'); });

    await t.step('body fills viewport', async () => {
      const body = t.page.locator('body').first();
      const box = await body.boundingBox();
      const vp = t.page.viewportSize();
      t.check('body visible', !!box, 'body not found');
      t.check('body width fills viewport',
        Math.abs(box.width - vp.width) < 20,
        \`body.width=\${box.width} viewport.width=\${vp.width}\`);
      await t.screenshot('body-layout');
    });

    // Example: assert a known element is visible and reasonably sized.
    // Uncomment and adapt the selector to your component.
    //
    // await t.step('nav bar visible', async () => {
    //   const nav = t.page.locator('nav, header').first();
    //   const box = await nav.boundingBox();
    //   t.check('nav found', !!box, 'nav element not in DOM');
    //   t.check('nav height > 40', box.height >= 40, \`nav.height=\${box.height}\`);
    //   t.check('nav not zero-width', box.width > 100, \`nav.width=\${box.width}\`);
    // });
  }
);
`,
  { skipIfExists: !FORCE },
);

// ── package.json ──────────────────────────────────────────────────────────────

{
  let pwVersion = '^1.45.0';
  // Try to read current playwright version from the skill's installed copy
  try {
    const pkgPath = path.join(SKILL_DIR, '..', '..', 'node_modules', 'playwright', 'package.json');
    if (fs.existsSync(pkgPath)) {
      const v = JSON.parse(fs.readFileSync(pkgPath, 'utf8')).version;
      if (v) pwVersion = `^${v}`;
    }
  } catch { /* use default */ }

  write(
    path.join(UI_DIR, 'package.json'),
    JSON.stringify({
      name: 'ui-tests',
      version: '1.0.0',
      type: 'module',
      description: 'Scaffolded UI test harness — see README.md',
      scripts: {
        test: 'node run.mjs --out .runs/latest --dir specs',
      },
      dependencies: {
        playwright: pwVersion,
      },
    }, null, 2) + '\n',
    { skipIfExists: !FORCE },
  );
}

// ── .gitignore ────────────────────────────────────────────────────────────────

write(
  path.join(UI_DIR, '.gitignore'),
  `.runs/\nnode_modules/\n`,
  { skipIfExists: !FORCE },
);

// ── README.md ─────────────────────────────────────────────────────────────────

write(
  path.join(UI_DIR, 'README.md'),
  `# UI Tests

Portable Playwright test harness scaffolded by the \`ui-test\` skill.
No dependency on the skill or assistant workspace after setup.

## Quick start

\`\`\`bash
# 1. Install deps (one-time)
cd tests/ui && npm install
npx playwright install --with-deps chromium

# 2. Set the app URL in config/apps.json
#    (e.g. http://localhost:8080)

# 3. Run the starter smoke spec
node run.mjs --out .runs/smoke specs/_example.smoke.mjs

# 4. Run all specs
node run.mjs --out .runs/all --dir specs
\`\`\`

Results (pass/fail + screenshots) are written under \`.runs/\` (gitignored).

## Credentials

Credentials stay out of the repo — pass them via environment variables:

\`\`\`bash
UITEST_APP_EMAIL=you@example.com UITEST_APP_PASSWORD=secret \\
  node run.mjs --out .runs/smoke specs/_example.smoke.mjs
\`\`\`

Variable names: \`UITEST_<APPKEY>_EMAIL\` / \`UITEST_<APPKEY>_PASSWORD\`
where \`<APPKEY>\` is the app key in \`config/apps.json\` (e.g. \`APP\` for key \`"app"\`).
Generic fallbacks: \`UITEST_EMAIL\` / \`UITEST_PASSWORD\`.

## Adding tests

1. Copy \`specs/_example.smoke.mjs\` to \`specs/your-feature.mjs\`.
2. Adjust the URL, selectors, and assertions.
3. Run: \`node run.mjs --out .runs/your-feature specs/your-feature.mjs\`

See the harness API in \`lib/harness.mjs\` for \`t.step\`, \`t.check\`, \`t.goto\`, \`t.screenshot\`.

## Refreshing the harness

Re-run the scaffold to update \`lib/\` and \`run.mjs\` from the skill without touching your specs:

\`\`\`bash
node skills/ui-test/script/scaffold.mjs . # from repo root (adjust path to skill location)
\`\`\`
`,
  { skipIfExists: !FORCE },
);

// ── Done ──────────────────────────────────────────────────────────────────────

console.log();
console.log('Scaffold complete.');
console.log();
console.log('Next steps:');
console.log(`  1. Edit ${path.relative(TARGET_REPO, path.join(UI_DIR, 'config', 'apps.json'))} — set the app URL.`);
console.log(`  2. cd ${path.relative(process.cwd(), UI_DIR)} && npm install`);
console.log(`     npx playwright install --with-deps chromium`);
console.log(`  3. node run.mjs --out .runs/smoke specs/_example.smoke.mjs`);
