#!/usr/bin/env bash
# scripts/install.sh — set up a Caravel workspace
#
# Usage (run once after cloning):
#
#   git clone https://github.com/caravelhq/caravel.git
#   cd caravel
#   bun install
#   bash scripts/install.sh
#
# What it does:
#   1. Asks where your workspace should live (any directory, new or existing).
#   2. Links the Caravel repo into <workspace>/repos/caravel/.
#   3. Seeds example agent profiles (alice, bob, ray) with task queues.
#   4. Installs the /task skill into <workspace>/.claude/skills/.
#   5. Generates restart-caravel.sh and start-caravel.sh at the workspace root.
#
# After install:
#   cd <workspace>
#   bash restart-caravel.sh     # start the daemon (backgrounded)
#   bash start-caravel.sh       # or run in the foreground (WSL auto-start)
#
# Re-running is safe — existing agent profiles and task queues are not overwritten.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ─── welcome ──────────────────────────────────────────────────────────────

cat <<'MSG'

  Caravel — workspace setup

  Caravel runs in a workspace directory, not inside the cloned repo itself.
  Your agents, task queues, notes, and projects all live in the workspace.
  The repo provides the daemon, skills, and templates — and stays separate.

MSG

# ─── 1. workspace directory ───────────────────────────────────────────────

DEFAULT_WORKDIR="${HOME}/caravel-workspace"
printf '  Workspace path [%s]: ' "$DEFAULT_WORKDIR"
IFS= read -r WORKDIR_INPUT
WORKDIR="${WORKDIR_INPUT:-$DEFAULT_WORKDIR}"

# Expand ~ and env vars; resolve to absolute path (creating the dir first).
WORKDIR="$(eval echo "$WORKDIR")"
mkdir -p "$WORKDIR"
WORKDIR="$(cd "$WORKDIR" && pwd)"

echo ""
echo "  Workspace: $WORKDIR"

# ─── 2. link the caravel repo ─────────────────────────────────────────────

REPO_LINK="${WORKDIR}/repos/caravel"
mkdir -p "${WORKDIR}/repos"

if [[ -e "$REPO_LINK" ]]; then
  echo "  repos/caravel/ already present — skipping link."
else
  ln -s "$REPO_ROOT" "$REPO_LINK"
  echo "  Linked repos/caravel/ → $REPO_ROOT"
fi

# ─── 3. seed agents + task system ─────────────────────────────────────────

echo ""
echo "  Installing agent profiles and task system..."
echo ""
CARAVEL_PROJECT_DIR="$WORKDIR" \
CARAVEL_REPO_DIR="$REPO_LINK" \
CARAVEL_SKIP_SYNC=1 \
  bash "${SCRIPT_DIR}/install-multi-agent.sh" --no-pull

# ─── 4. generate workspace start/restart scripts ──────────────────────────

echo ""
echo "  Generating workspace scripts..."

_write_caller() {
  local dest="$1"
  local extra_args="${2:-}"
  local desc="${3:-Caravel daemon control script.}"
  local name
  name="$(basename "$dest")"

  if [[ -e "$dest" ]]; then
    echo "  ${name} already exists — skipping."
    return
  fi

  {
    printf '#!/usr/bin/env bash\n'
    printf '# %s\n' "$desc"
    printf '# Generated by: bash repos/caravel/scripts/install.sh\n'
    printf '# Re-run the installer to regenerate this file.\n'
    printf 'set -euo pipefail\n\n'
    printf 'WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n\n'
    printf 'export CARAVEL_PROJECT_DIR="$WORKDIR"\n'
    printf 'export CARAVEL_REPO_DIR="${WORKDIR}/repos/caravel"\n'
    printf 'export CARAVEL_MULTI_AGENT_RUNNER=1\n\n'
    printf '# Run from the Claude Code plugin cache when present (keeps Claude Code workers in\n'
    printf '# sync with this fork); fall back to running from the repo source directly.\n'
    printf '# This means the daemon works whether or not you have Claude Code installed.\n'
    printf '_PLUGIN_CACHE="${HOME}/.claude/plugins/cache/claudeclaw/claudeclaw/1.0.0/src/index.ts"\n'
    printf 'if [[ ! -f "$_PLUGIN_CACHE" ]]; then\n'
    printf '  export CARAVEL_PLUGIN_ENTRY="${CARAVEL_REPO_DIR}/src/index.ts"\n'
    printf '  export CARAVEL_SKIP_SYNC=1\n'
    printf 'fi\n\n'
    printf '# Uncomment to run a command before the daemon starts (e.g. connect Tailscale):\n'
    printf '# export CARAVEL_PRESTART_HOOK="tailscale up"\n\n'
    printf '# Source LiteLLM / provider API keys if present:\n'
    printf 'if [[ -f "${HOME}/.litellm.env" ]]; then\n'
    printf '  # shellcheck disable=SC1091\n'
    printf '  source "${HOME}/.litellm.env"\n'
    printf '  export GEMINI_API_KEY LITELLM_MASTER_KEY 2>/dev/null || true\n'
    printf 'fi\n\n'
    if [[ -n "$extra_args" ]]; then
      printf 'exec bash "${WORKDIR}/repos/caravel/scripts/restart-caravel.sh" %s "$@"\n' "$extra_args"
    else
      printf 'exec bash "${WORKDIR}/repos/caravel/scripts/restart-caravel.sh" "$@"\n'
    fi
  } > "$dest"
  chmod +x "$dest"
  echo "  Created ${name}"
}

_write_caller \
  "${WORKDIR}/restart-caravel.sh" \
  "" \
  "Restart the Caravel daemon (backgrounded via nohup)."

_write_caller \
  "${WORKDIR}/start-caravel.sh" \
  "--foreground" \
  "Start the Caravel daemon in the foreground (use for WSL auto-start)."

# ─── 5. check claude code plugin (informational) ──────────────────────────

echo ""
echo "  Checking Claude Code plugin (optional)..."

PLUGIN_CACHE="${HOME}/.claude/plugins/cache/claudeclaw/claudeclaw/1.0.0/src/index.ts"
if [[ -f "$PLUGIN_CACHE" ]]; then
  echo "  Found — daemon will sync Caravel source into the Claude Code plugin cache."
  PLUGIN_PRESENT=1
else
  echo "  Not found — daemon will run directly from the repo source (no plugin needed)."
  PLUGIN_PRESENT=0
fi

# ─── done ─────────────────────────────────────────────────────────────────

cat <<MSG

  Done.

  Your Caravel workspace is at:
    ${WORKDIR}

  Customise your roster (the example profiles are a starting point):
    ${WORKDIR}/agents/alice/CLAUDE.md   <- the coordinator
    ${WORKDIR}/agents/bob/CLAUDE.md     <- specialist (builder)
    ${WORKDIR}/agents/ray/CLAUDE.md     <- specialist (researcher)

  Need to move this workspace later?
    Update the symlink: repos/caravel -> /new/path/to/the/repo

MSG

cat <<MSG
  Start your crew:
    cd ${WORKDIR}
    bash restart-caravel.sh

  Dashboard:
    http://127.0.0.1:4632

MSG

if [[ $PLUGIN_PRESENT -eq 0 ]]; then
  cat <<MSG
  Note: Claude Code plugin not found — the daemon will run from repo source directly.
  This works fine for any agent CLI. If you later install the claudeclaw plugin
  (/plugin install claudeclaw in a Claude Code session), the daemon will sync to
  the plugin cache automatically on next start.

MSG
fi
